kind: Service
apiVersion: v1
metadata:
  name: redis-service
  namespace: sify-assessment
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - name: redis-port
      port: 6379
      targetPort: 6379
