version: "3.8"

services:
  frontend:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - backend
  backend:
    build: ./backend
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
