apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: sify-assessment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: aakashb1408/sify-assessment-frontend:v1.0
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi

          ports:
            - containerPort: 80
