kind: Service
apiVersion: v1
metadata:
  name: flask-service
  namespace: flask-ns
spec:
  selector:
    app: flask
  type: ClusterIP
  ports:
    - name: flask-port
      port: 5000
      targetPort: 5000
