apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: flask-ns
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 1

  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: aakashb1408/sify-assessment-backend:v1.3
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 50Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: flask-redis-cm
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: REDIS_PASSWORD
          ports:
            - containerPort: 5000
              name: flask
